Repository Jaseci-Labs/jaclang, pull requests merged in 2024-04, with the labels that each got.

#282 [FIX] Added the Semstrings to Global Variables and Enum Stmts
  jaclang/compiler/absyntree.py
  jaclang/compiler/jac.lark
  jaclang/compiler/parser.py
  jaclang/compiler/passes/main/pyast_gen_pass.py
  jaclang/tests/fixtures/semstr.jac
Labels: enhancement

#275 [FEATURE] JAC Register v0.1
  jaclang/compiler/absyntree.py
  jaclang/compiler/parser.py
  jaclang/compiler/passes/main/__init__.py
  jaclang/compiler/passes/main/registry_pass.py
  jaclang/compiler/passes/main/schedules.py
  jaclang/compiler/passes/main/tests/fixtures/registry.jac
  jaclang/compiler/passes/main/tests/test_registry_pass.py
  jaclang/core/registry.py
  jaclang/tests/fixtures/registry.jac
  jaclang/tests/test_language.py
Labels: enhancement

#286 [FEATURE] AOTT Raise
  jaclang/compiler/absyntree.py
  jaclang/compiler/passes/main/pyast_gen_pass.py
  jaclang/compiler/passes/main/registry_pass.py
  jaclang/core/aott.py
  jaclang/core/registry.py
  jaclang/core/utils.py
  jaclang/plugin/default.py
  jaclang/plugin/feature.py
  jaclang/plugin/spec.py
  jaclang/tests/fixtures/aott_raise.jac
  jaclang/tests/fixtures/registry.jac
  jaclang/tests/fixtures/with_llm.jac
  jaclang/tests/fixtures/with_llm_function.jac
  jaclang/tests/fixtures/with_llm_method.jac
  jaclang/tests/test_language.py
Labels: enhancement

#303 [FEATURE] AOTT Lower
  jaclang/compiler/passes/main/pyast_gen_pass.py
  jaclang/core/aott.py
  jaclang/plugin/default.py
  jaclang/tests/fixtures/with_llm_function.jac
  jaclang/tests/fixtures/with_llm_lower.jac
  jaclang/tests/fixtures/with_llm_method.jac
  jaclang/tests/test_language.py
Labels: enhancement

#319 able to Declare Enum Inside Architype
  jaclang/compiler/absyntree.py
  jaclang/tests/fixtures/enum_inside_archtype.jac
  jaclang/tests/test_language.py
Labels: bug fix

#317 [FEATURE] By LLM Type Syntax
  connect_expressions.dot
  jaclang/compiler/absyntree.py
  jaclang/compiler/jac.lark
  jaclang/compiler/parser.py
  jaclang/compiler/passes/main/pyast_gen_pass.py
  jaclang/compiler/passes/main/pyast_load_pass.py
  jaclang/core/aott.py
  jaclang/core/registry.py
  jaclang/core/utils.py
  jaclang/plugin/default.py
  jaclang/plugin/feature.py
  jaclang/plugin/spec.py
  jaclang/tests/fixtures/with_llm_type.jac
  jaclang/tests/test_language.py
Labels: enhancement

#262 [DOCUMENTATION] Semstring and With LLM
  support/jac-lang.org/docs/learn/guide.md
  support/jac-lang.org/docs/learn/with_llm.md
  support/jac-lang.org/mkdocs.yml
Labels: documentation

#327 [DOCUMENTATION] By LLM Examples
  examples/genai/essay_review.jac
  examples/genai/expert_answer.jac
  examples/genai/joke_gen.jac
  examples/genai/odd_word_out.jac
  examples/genai/personality_finder.jac
  examples/genai/text_to_type.jac
  examples/genai/translator.jac
  examples/genai/wikipedia.jac
  jaclang/compiler/passes/tool/jac_formatter_pass.py
  jaclang/core/llms.py
Labels: documentation
