Repository Jaseci-Labs/jaclang, pull requests merged in 2024-05, with the labels that each got.

#352 [BUG FIX] - Try stmt and Star Tuple unpack
  jaclang/compiler/absyntree.py
  jaclang/compiler/jac.lark
  jaclang/compiler/parser.py
  jaclang/compiler/passes/main/pyast_gen_pass.py
  jaclang/compiler/passes/main/sym_tab_build_pass.py
  jaclang/compiler/passes/tool/jac_formatter_pass.py
  jaclang/tests/fixtures/arithmetic_bug.jac
  jaclang/tests/fixtures/lambda.jac
  jaclang/tests/fixtures/try_finally.jac
  jaclang/tests/fixtures/tupleunpack.jac
  jaclang/tests/test_language.py
Labels: bug fix

#356 Grammer checking llm example
  examples/genai/grammar_checker.jac
Labels: documentation

#382 fix: optional semstr for genai_ability
  jaclang/compiler/passes/main/pyast_gen_pass.py
  jaclang/tests/fixtures/semstr.jac
Labels: bug fix

#380 Split Import pass
  jaclang/compiler/passes/main/__init__.py
  jaclang/compiler/passes/main/import_pass.py
  jaclang/compiler/passes/main/schedules.py
  jaclang/compiler/passes/main/tests/test_import_pass.py
  jaclang/tests/test_language.py
Labels: enhancement

#377 [Documentation] Opensource LLM Examples
  examples/genai/essay_review.jac
  examples/genai/expert_answer.jac
  examples/genai/joke_gen.jac
  examples/genai/odd_word_out.jac
  examples/genai/personality_finder.jac
  examples/genai/text_to_type.jac
  examples/genai/translator.jac
  examples/genai/wikipedia.jac
  jaclang/core/aott.py
  jaclang/core/llms.py
  jaclang/core/llms/__init__.py
  jaclang/core/llms/anthropic.py
  jaclang/core/llms/groq.py
  jaclang/core/llms/huggingface.py
  jaclang/core/llms/ollama.py
  jaclang/plugin/default.py
  jaclang/tests/fixtures/aott_raise.jac
  jaclang/tests/fixtures/with_llm_function.jac
  jaclang/tests/fixtures/with_llm_lower.jac
  jaclang/tests/fixtures/with_llm_method.jac
  jaclang/tests/fixtures/with_llm_type.jac
  jaclang/tests/test_language.py
  setup.py
Labels: documentation, enhancement
